### ISSUE TITLE
`CLANG_INCLUDE_DIRS` should be added to include directories.

### ISSUE THREAD

**Issue by sinotca529** [trailofbits/vast#324]
Hi! Thanks for the great tool!

Compile with LLVM 16.0.6 (built from source codes) failed.
One of the compile-time errors I faced :

```
In file included from /home/.../vast/lib/vast/CodeGen/FunctionInfo.cpp:3:
/home/.../vast/include/vast/CodeGen/FunctionInfo.hpp:6:10: fatal error: 'clang/AST/Decl.h' file not found
#include <clang/AST/Decl.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

I think this error is caused because `clang/include` is not contained in include directories.
To fix the problem, I think CMakeLists.txt should be modified as:

```
 # TODO(Heno): clean up & modernize
 include_directories(${LLVM_INCLUDE_DIRS})
 include_directories(${MLIR_INCLUDE_DIRS})
+include_directories(${CLANG_INCLUDE_DIRS})
```

After this modification, I checked that the build and the test is successful.
I made the fix on [my fork](https://github.com/sinotca529/vast/tree/fix/include-dir).
May I make a PR?

<details>
<summary>Information of the build step I tried</summary>

## Environment 
Ubuntu 22.04.2 LTS (on WSL2)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

## Build command for LLVM16.0.6
```
cmake \
    -G Ninja \
    -DLLVM_USE_LINKER=gold \
    -DLLVM_ENABLE_PROJECTS="clang;mlir" \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DLLVM_USE_SPLIT_DWARF=ON \
    -DLLVM_TARGETS_TO_BUILD="X86" \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DLLVM_ENABLE_RTTI=ON \
    -B build \
    llvm

cmake --build build
```

## Build command for VAST
```
LLVM_BUILD_DIR=$HOME/llvm-project/build

cmake \
    --preset ninja-multi-default \
    --toolchain ./cmake/lld.toolchain.cmake \
    -DCMAKE_PREFIX_PATH=$LLVM_BUILD_DIR/lib/cmake \
    -DCMAKE_CXX_COMPILER=$LLVM_BUILD_DIR/bin/clang++ \
    -DCMAKE_C_COMPILER=$LLVM_BUILD_DIR/bin/clang
```

</details>

**Comment by pgoodman** [comment]
@sinotca529 Can you submit a PR? At the same time, can you convert `include_directories` to `target_include_directories`?

**Comment by sinotca529** [comment]
> can you convert include_directories to target_include_directories?

I think the conversion will take a lot of time for me, a beginner in MLIR.
I searched usage of `MLIR_INCLUDE_DIRS` [on GitHub](https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29.*.txt%24%2F+MLIR_INCLUDE_DIRS&type=code&p=2), but a good pattern with `target_include_directories` does not found yet.

So, I would like to leave the conversion issue to someone else. Sorry.
If adding only `include_directories(${CLANG_INCLUDE_DIRS})` is acceptable, I can submit a PR.

**Comment by pgoodman** [comment]
Sure, you can submit a PR with just the clang include dirs change. For context, `include_directories` and `target_include_directories` relate to CMake. E.g. https://cmake.org/cmake/help/latest/command/target_include_directories.html

**Comment by sinotca529** [comment]
Thanks for the information!
I submitted a PR (#325).

---

It may be useless information, but I'll note what I did.
I tried to add target_include_directories after some add_library commands like below.

```
add_library(vast_frontend_tool
  compiler_invocation.cpp
)

target_include_directories(vast_frontend_tool PRIVATE
  ${LLVM_INCLUDE_DIRS}
  ${CLANG_INCLUDE_DIRS}
  ${MLIR_INCLUDE_DIRS}
)
```

However, a compile-time error was caused.

```
[1/144] Building LowLevel.cpp.inc...
FAILED: include/vast/Dialect/LowLevel/LowLevel.cpp.inc /home/... 

.../vast/include/vast/Dialect/LowLevel/LowLevel.td:6:9: error: Could not find include file 'mlir/IR/OpBase.td'
include "mlir/IR/OpBase.td"
        ^
.../vast/include/vast/Dialect/LowLevel/LowLevel.td:6:9: error: Unexpected token at top level
include "mlir/IR/OpBase.td"
        ^
ninja: build stopped: subcommand failed.

```

I think this error relates to `add_mlir_dialect_library(MLIRLowLevel ...)` but I could not solve this.

**Comment by pgoodman** [comment]
You should mark them `PUBLIC` in the `target_include_directories`. Anyway, the PR looks good.

**Comment by pgoodman** [comment]
I await @lkorenc's approval, as he may want to rename the PR or github message.
